theme: jekyll-theme-midnight
title: Dhruv Thippasandra
description: "All about me"
email: "dhruvthug@gmail.com"
webserverid: "dhruvthippasandra"
twitter: "https://twitter.com/dhruvt"
twitterid: "dhruvt"
