theme: jekyll-theme-midnight
title: Dhruv Thippasandra
description: "All about me"
#gitorg: "https://github.com/suneelanaidu"
email: "dhruvthug@gmail.com"
#webserver: "https://github.com/suneelanaidu/DhruvThippasandra"
webserverid: "dhruvthippasandra"
twitter: "https://twitter.com/dhruvt"
twitterid: "dhruvt"
